# Generated by Django 3.2.25 on 2024-06-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_web_app', '0003_rename_state_icon_computer_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='warning',
            field=models.BooleanField(default=False),
        ),
    ]
