# Generated by Django 3.2.25 on 2024-06-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_web_app', '0004_computer_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
