# Generated by Django 3.2.25 on 2024-06-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_web_app', '0005_alter_computer_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='exam_mode',
            field=models.BooleanField(default=False),
        ),
    ]
