# Generated by Django 3.2.25 on 2024-05-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='computer',
            name='state_icon',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
