---
- name: Alternar a modo examen
  hosts: "{{ target_host | default('online') }}"
  become: yes
  tasks:
    - name: Detener servicio LightDM normal
      systemd:
        name: lightdm
        state: stopped

    - name: Detener servicio LightDM examen (si está activo)
      systemd:
        name: lightdm_exam
        state: stopped
      ignore_errors: yes

    - name: Esperar 1 segundo
      pause:
        seconds: 3

    - name: Copiar configuración de LightDM para modo examen
      copy:
        src: /etc/lightdm/lightdm.conf.exam
        dest: /etc/lightdm/lightdm.conf
        owner: root
        group: root
        mode: '0644'

    - name: Iniciar servicio LightDM examen
      systemd:
        name: lightdm_exam
        state: started
        enabled: yes

    - name: Esperar 1 segundo
      pause:
        seconds: 1

    - name: Reiniciar LightDM para aplicar los cambios
      systemd:
        name: lightdm_exam
        state: restarted
