---
- name: Alternar a modo normal
  hosts: "{{ target_host | default('online') }}"
  become: yes
  tasks:
    - name: Detener servicio LightDM examen
      systemd:
        name: lightdm_exam
        state: stopped

    - name: Detener servicio LightDM normal (si está activo)
      systemd:
        name: lightdm
        state: stopped
      ignore_errors: yes

    - name: Esperar 1 segundo
      pause:
        seconds: 1

    - name: Iniciar servicio LightDM normal
      systemd:
        name: lightdm
        state: started
        enabled: yes
