# /home/administrador/Documentos/Repositorios/tfg_app_web_proyecto/ansible/playbooks/clone_exm_user.yml
---
- name: Clonar perfil de usuario 'modo_examen' en todos los hosts
  hosts: online
  become: yes
  tasks:
    - name: Crear usuario 'modo_examen'
      user:
        name: modo_examen
        state: present
        password: "$6$dnxO43JU50C$4hnHktojGLemDZNRh8ydwQK.8Tx9QQuZQ.4EqsDQyGV0iTPuQlpFsU0bsll4nNFc7JclPIV6vY//isArRFqI6/"
        shell: /bin/bash
        update_password: always

    - name: Asegurarse de que el directorio home existe
      file:
        path: /home/modo_examen
        state: directory
        owner: modo_examen
        group: modo_examen

    - name: Sincronizar el directorio home desde el servidor a los hosts
      synchronize:
        src: /home/modo_examen/
        dest: /home/modo_examen/
        archive: yes
        delete: no
        recursive: yes
      delegate_to: localhost

    - name: Copiar .bashrc desde el servidor a los hosts
      copy:
        src: /home/modo_examen/.bashrc
        dest: /home/modo_examen/.bashrc
        owner: modo_examen
        group: modo_examen
        mode: '0644'

    - name: Copiar .profile desde el servidor a los hosts
      copy:
        src: /home/modo_examen/.profile
        dest: /home/modo_examen/.profile
        owner: modo_examen
        group: modo_examen
        mode: '0644'

    - name: Copiar configuraci贸n de LightDM para modo normal desde el servidor a los hosts
      copy:
        src: /home/modo_examen/lightdm_conf_files/lightdm.conf.normal
        dest: /etc/lightdm/lightdm.conf.normal
        owner: root
        group: root
        mode: '0644'

    - name: Copiar configuraci贸n de LightDM para modo examen desde el servidor a los hosts
      copy:
        src: /home/modo_examen/lightdm_conf_files/lightdm.conf.exam
        dest: /etc/lightdm/lightdm.conf.exam
        owner: root
        group: root
        mode: '0644'

    - name: Copiar script de inicio de sesi贸n personalizado desde el servidor a los hosts
      copy:
        src: /home/modo_examen/exam_login_script.sh
        dest: /home/modo_examen/exam_login_script.sh
        owner: modo_examen
        group: modo_examen
        mode: '0755'

    - name: Copiar fondo de pantalla del modo examen desde el servidor a los hosts
      copy:
        src: /home/modo_examen/bckg_exm_mode.jpg
        dest: /home/modo_examen/bckg_exm_mode.jpg
        owner: modo_examen
        group: modo_examen
        mode: '0777'

    - name: Copiar lightdm_exam.service desde el servidor a los hosts
      copy:
        src: /home/modo_examen/lightdm_exam.service
        dest: /etc/systemd/system/lightdm_exam.service
        owner: root
        group: root
        mode: '0644'

    - name: Copiar archivo de configuraci贸n de AccountsService para modo_examen
      copy:
        src: /var/lib/AccountsService/user/modo_examen
        dest: /var/lib/AccountsService/user/modo_examen
        owner: root
        group: root
        mode: '0644'

    - name: Recargar systemd para detectar nuevos servicios
      systemd:
        daemon_reload: yes
