# /home/administrador/Documentos/Repositorios/tfg_app_web_proyecto/ansible/playbooks/create_exm_user.yml
---
- name: Crear y configurar perfil de usuario 'modo_examen' en el servidor
  hosts: localhost
  become: yes
  tasks:
    - name: Crear usuario 'modo_examen'
      user:
        name: modo_examen
        state: present
        shell: /bin/bash
        password: "$6$dnxO43JU50C$4hnHktojGLemDZNRh8ydwQK.8Tx9QQuZQ.4EqsDQyGV0iTPuQlpFsU0bsll4nNFc7JclPIV6vY//isArRFqI6/"
        update_password: always

    - name: Crear directorio home para 'modo_examen'
      file:
        path: /home/modo_examen
        state: directory
        owner: modo_examen
        group: modo_examen

    - name: Copiar .bashrc
      copy:
        src: /home/administrador/Documentos/Repositorios/tfg_app_web_proyecto/registers/config_exm_files/.bashrc
        dest: /home/modo_examen/.bashrc
        owner: modo_examen
        group: modo_examen
        mode: '0644'

    - name: Copiar .profile
      copy:
        src: /home/administrador/Documentos/Repositorios/tfg_app_web_proyecto/registers/config_exm_files/.profile
        dest: /home/modo_examen/.profile
        owner: modo_examen
        group: modo_examen
        mode: '0644'

    - name: Crear directorio lightdm_conf_files
      file:
        path: /home/modo_examen/lightdm_conf_files
        state: directory
        owner: modo_examen
        group: modo_examen

    - name: Copiar configuración de LightDM para modo normal
      copy:
        src: /home/administrador/Documentos/Repositorios/tfg_app_web_proyecto/registers/config_exm_files/lightdm.conf.normal
        dest: /home/modo_examen/lightdm_conf_files/lightdm.conf.normal
        owner: modo_examen
        group: modo_examen
        mode: '0644'

    - name: Copiar configuración de LightDM para modo examen
      copy:
        src: /home/administrador/Documentos/Repositorios/tfg_app_web_proyecto/registers/config_exm_files/lightdm.conf.exam
        dest: /home/modo_examen/lightdm_conf_files/lightdm.conf.exam
        owner: modo_examen
        group: modo_examen
        mode: '0644'

    - name: Copiar script de inicio de sesión personalizado
      copy:
        src: /home/administrador/Documentos/Repositorios/tfg_app_web_proyecto/registers/config_exm_files/exam_login_script.sh
        dest: /home/modo_examen/exam_login_script.sh
        owner: modo_examen
        group: modo_examen
        mode: '0755'

    - name: Copiar fondo de pantalla
      copy:
        src: /home/administrador/Documentos/Repositorios/tfg_app_web_proyecto/registers/config_exm_files/bckg_exm_mode.jpg
        dest: /home/modo_examen/bckg_exm_mode.jpg
        owner: modo_examen
        group: modo_examen
        mode: '0777'

    - name: Copiar lightdm_exam.service
      copy:
        src: /home/administrador/Documentos/Repositorios/tfg_app_web_proyecto/registers/config_exm_files/lightdm_exam.service
        dest: /home/modo_examen/lightdm_exam.service
        owner: modo_examen
        group: modo_examen
        mode: '0644'
