---
- name: Apagar máquinas en línea
  hosts: "{{ target_host | default('localhost') }}"
  tasks:
    - name: Apagar máquinas en el grupo [online]
      shell: |
        shutdown -h now
        sleep 10  # Espera 10 segundos para permitir que la máquina se apague completamente
      delegate_to: "{{ item }}"
      become: yes
      become_method: sudo
      ignore_errors: yes  # Ignora errores de conexión, ya que la máquina se está apagando
      with_items: "{{ groups['online'] if target_host is undefined else [target_host] }}"
    - name: Verificar que las máquinas se han apagado
      wait_for_connection:
        delay: 30  # Espera 30 segundos antes de verificar la conexión
        timeout: 180  # Tiempo máximo para esperar la conexión
        sleep: 5  # Espera 5 segundos entre intentos de conexión
      delegate_to: "{{ item }}"
      ignore_unreachable: yes  # Ignora las máquinas inaccesibles, ya que pueden estar apagadas
      with_items: "{{ groups['online'] if target_host is undefined else [target_host] }}"