---
- name: Escanear red local
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Escanear red local
      ansible.builtin.ping:
        count: 3
      register: ping_result
      ignore_errors: yes

    - name: Crear lista de hosts que respondieron al ping
      set_fact:
        live_hosts: "{{ ping_result | selectattr('ansible_facts.ping', 'defined') | map(attribute='ansible_host') | list }}"

    - name: Escribir inventario dinámico
      template:
        src: templates/inventory_template.ini.j2
        dest: "{{ playbook_dir }}/inventory.ini"
