---
- name: Ejecutar script de escaneo en localhost
  hosts: localhost
  tasks:
    - name: Ejecutar script
      shell: "{{ script_path }} {{ search_string }}"
      register: script_output

    - name: Guardar salida del script
      copy:
        content: "{{ script_output.stdout_lines | join('\n') }}"
        dest: "{{ output_directory }}/ansible_scan_output.log"
      delegate_to: localhost

  vars:
      script_path: "{{ lookup('env', 'HOME') }}/Documentos/Repositorios/tfg_app_web_proyecto/app/admin_web_app/management/bash/scan_lab_by_arp.sh"
      search_string: "p1-019-"
      output_directory: "{{ lookup('env', 'HOME') }}/Documentos/Repositorios/tfg_app_web_proyecto/outputs"

