- name: Update and upgrade packages on remote machine
  hosts: localhost
  become: yes
  vars:
    target_host: "{{ target_host }}"
  tasks:
    - name: Ensure target host is reachable
      wait_for_connection:
        timeout: 300
      delegate_to: "{{ target_host }}"

    - name: Update APT package list
      command: apt-get update
      delegate_to: "{{ target_host }}"
      become: yes

    - name: Upgrade all APT packages
      command: apt-get upgrade -y
      delegate_to: "{{ target_host }}"
      become: yes

    - name: Auto-remove unused packages
      command: apt-get autoremove -y
      delegate_to: "{{ target_host }}"
      become: yes

    - name: Run custom command
      command: "{{ custom_command }}"
      delegate_to: "{{ target_host }}"
      become: yes
      when: custom_command is defined

    - name: Reboot the machine if custom_command is not defined
      command: shutdown -r now
      delegate_to: "{{ target_host }}"
      become: yes
      async: 0
      poll: 0
      ignore_errors: yes
      when: custom_command is not defined
